### PR TITLE
Take randomness from system, as function pointer

### LINKED ISSUE #88: Fix randomly-occuring travis-ci failures around `prng_init`
Every once in a while, a travis build will fail, but then succeed when re-run. The error is that `prng_init` fails.

Most likely, the sufficient-entropy check in the init function is failing on the travis VMs.

### LINKED ISSUE #96: Examine how to take randomness
Currently, we obtain a random seed from a call to libsodium's `randombytes_buf`, or allow the user to supply the random seed, then use that to seed a userspace csprng which is then used for all subsequent randomness.

It may be wise to eschew the userspace csprng and just take randomness from some user-specified system source (e.g. `getrandom` or `arc4random` or just reading from `/dev/urandom`). 

This is currently a commonly-recommended practice from many crypto experts (eg. [DJB on urandom](https://blog.cr.yp.to/20140205-entropy.html).

Some of the perils of using a userspace csprng include (to my knowledge):
- Rather than relying on a second codebase (the implementation of the csprng), which will still rely on proper seeding that came from the system's randomness, just use the system's randomness and rely on all the kernel devs maintaining that properly
- Forking can cause problems, if the new process gets the exact same rng memory layout

Libsodium's `randombytes_buf` handles all that for us, but we just use it for seeding. We could just use randombytes_buf, but we also want to support platforms that may not be supported by libsodium.

So, maybe just be totally agnostic to this decision, and allow the user to specify this (and indicate that the common best answer will be, on recent-enough Linux, to use `getrandom`). That's putting a lot of power in the hands of the user, but may be the best way forward.

### PR DESCRIPTION
**Pull request by zanebeckwith**
This removes the `ecdaa_prng` user-space cryptographically-secure random number generator (which was just a wrapper around AMCL's csprng), in favor of taking a function-pointer from the user that gives us random numbers directly. The intention (and what is illustrated in the examples) is that this function will use the system's source of randomness (e.g. `getrandom` on Linux, or just `/dev/urandom`).

This is done for two reasons:
- General cryptographic best practice currently recommends against using user-space csprngs, and instead drawing directly from system-provided sources. In our case, this is largely to avoid extra crypto code that hasn't had the same code review as the system-provided sources.
- It would be nice to not have to link against libsodium in this library. Previously, we had to simply to get access to their `randombytes_buf` function, which is just a cross-platform wrapper around system-provided sources of randomness. Now, we suggest that `randombytes_buf` is a good choice, but we don't require it and instead use our own (stripped-down, fewer-platform-supporting) implementation of `randombytes_buf` in the examples.

Fixes #96 
Also, because we no longer use `randombytes_buf` in our tests, and thus no longer check that the system's csprng has been properly seeded (we have a warning about this in the README), we shouldn't get the intermittent errors in travis-ci that we had before. So, this Fixes #88.

### CODE REVIEW

File: common/amcl-extensions/ecp_ZZZ.c [hunk 1]
```diff
@@ -121,12 +126,54 @@ int32_t ecp_ZZZ_fromhash(ECP_ZZZ *point_out, const uint8_t *message, uint32_t me
...
 void ecp_ZZZ_random_mod_order(BIG_XXX *big_out,
-                              csprng *rng)
+                              void (*get_random)(void *buf, size_t buflen))
 {
+    // 1) Get the order of the group
     BIG_XXX curve_order;
     BIG_XXX_rcopy(curve_order, CURVE_Order_ZZZ);
 
-    BIG_XXX_randomnum(*big_out, curve_order, rng);
+    // 2) Fill our pool with randomness (will be replenished if needed)
```
Comment (drbild) [inline common/amcl-extensions/ecp_ZZZ.c]: What's the purpose of the pool?  Just an speed optimization versus doing `get_random(&r, 1)` in the main loop?

The pool management stuff seems out place in this function and the `get_random_byte` function out of place in this file.  Should the generic pool management stuff be in `ecdaa/randomness.h`?

File: README.md [hunk 2]
```diff
@@ -174,25 +171,26 @@ where `credential` is an ECDAA credential obtained earlier and `prng` is an `ecd
...
-require a pseudo random number generator (type `ecdaa_prng`).
-The security of these algorithms depends critically on the proper seeding of this prng.
-This means that the first use of any `ecdaa_prng` MUST be preceeded by a call to
-`ecdaa_prng_init` (or `ecdaa_prng_init_custom`, see below) on the prng.
+require a source of cryptographically-secure random numbers.
 
-In `ecdaa_prng_init`, the seed for the `ecdaa_prng` is generated from Libsodium's
-`randombytes_buf` function.
-A discussion on how this function works and any caveats can be found at Libsodium's webpage.
+Such functions take a parameter of type `ecdaa_randomness_func_t`,
```
Comment (drbild) [inline README.md]: Can that name (and the associated header file name) be shortened?  Any reason to prefer `randomness` to `rand` or `random`?

Somewhat related, what's the reason for the `_t` suffix?  Would just `ecdaa_rand_func` suffice?  Some of the names get really lengthy and make it hard to fit even a one-parameter function call on one line.

File: common/amcl-extensions/ecp_ZZZ.c [hunk 3]
```diff
@@ -121,12 +126,54 @@ int32_t ecp_ZZZ_fromhash(ECP_ZZZ *point_out, const uint8_t *message, uint32_t me
...
+    uint8_t randomness_pool[MAX_RANDOMNESS_POOL_SIZE];
+    size_t needed_random_bytes = (size_t)(1 + 2*BIG_XXX_nbits(curve_order) / 8);
+    size_t randomness_pool_size = needed_random_bytes>MAX_RANDOMNESS_POOL_SIZE ? MAX_RANDOMNESS_POOL_SIZE : needed_random_bytes;
+    get_random(randomness_pool, randomness_pool_size);
+    uint8_t *pool_ptr = randomness_pool;
+
+    // 3) Generate a random BIG bit-by-bit,
+    //      then reduce it modulo the group order.
+    // ZVB 2018-04-27: Adapted from AMCL big.c.in::BIG_XXX_randomnum() function
```
[the remark this answers is not in the document]
Comment (zanebeckwith) [reply common/amcl-extensions/ecp_ZZZ.c]: Ha, that's funny. That's a holdover from my previous job. Yea, I'll remove those.

File: common/amcl-extensions/ecp_ZZZ.c (hunk 1 above)
Comment (zanebeckwith) [reply common/amcl-extensions/ecp_ZZZ.c]: Yea, the pool is an optimization. 

I can put the pool management stuff in a separate `common/internal-utils` file. But, since it's for our internal use and not for the end user, I don't think it should go in `randomness.h`.

File: README.md (hunk 2 above)
Comment (zanebeckwith) [reply README.md]: Yea, good call. I have a tendency to get really verbose with my naming. `ecdaa_rand_func` in the file `rand.h` works for me.

**Comment by zanebeckwith** [comment]
@drbild I shortened the names, and moved the pool-related stuff into a separate file, under `common/internal-utilities`.

Let me know what you think.

**Comment by drbild** [comment]
Looks like the README needs the `ecdaa_randomness_func_t` to `ecdaa_rand_func` change too.  

Also, should the pool stuff become `ecdaa_rand_pool` rather than `ecdaa_randomness_pool`, etc?

**Comment by zanebeckwith** [comment]
Rargh, good catch on the names.

Alright, now, fixed. Sorry.

File: libecdaa/include/ecdaa/rand.h [hunk 4]
```diff
@@ -0,0 +1,41 @@
...
+ * 
+ *    Unless required by applicable law or agreed to in writing, software
+ *    distributed under the License is distributed on an "AS IS" BASIS,
+ *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ *    See the License for the specific language governing permissions and
+ *    limitations under the License
+ *
+ *****************************************************************************/
+
+#ifndef ECDAA_RANDOMNESS_H
```
Comment (drbild) [inline libecdaa/include/ecdaa/rand.h]: Ooops, I missed this one last time.  `ECDAA_RAND_H`
